name: password_cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  _discoveryapis_commons: ^1.0.3
  args: ^2.3.1
  csv: ^5.0.1
  encrypt: ^5.0.1
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  intl: ^0.17.0
  logging: ^1.1.0
  pointycastle: ^3.6.2
  tabler: ^1.0.2

executables:
  bpass: password_cli
